'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("c:\")>  _
        Public Property pic_path() As String
            Get
                Return CType(Me("pic_path"),String)
            End Get
            Set
                Me("pic_path") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property texture_win_location() As Global.System.Drawing.Point
            Get
                Return CType(Me("texture_win_location"),Global.System.Drawing.Point)
            End Get
            Set
                Me("texture_win_location") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("783, 381")>  _
        Public Property texture_win_client_size() As Global.System.Drawing.Size
            Get
                Return CType(Me("texture_win_client_size"),Global.System.Drawing.Size)
            End Get
            Set
                Me("texture_win_client_size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("c:\")>  _
        Public Property txt_path() As String
            Get
                Return CType(Me("txt_path"),String)
            End Get
            Set
                Me("txt_path") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("192.168.24.106")>  _
        Public Property server_address() As String
            Get
                Return CType(Me("server_address"),String)
            End Get
            Set
                Me("server_address") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("75")>  _
        Public Property brightness() As Integer
            Get
                Return CType(Me("brightness"),Integer)
            End Get
            Set
                Me("brightness") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vr_700() As Boolean
            Get
                Return CType(Me("vr_700"),Boolean)
            End Get
            Set
                Me("vr_700") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vr_400() As Boolean
            Get
                Return CType(Me("vr_400"),Boolean)
            End Get
            Set
                Me("vr_400") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vr_900() As Boolean
            Get
                Return CType(Me("vr_900"),Boolean)
            End Get
            Set
                Me("vr_900") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property vr_1200() As Boolean
            Get
                Return CType(Me("vr_1200"),Boolean)
            End Get
            Set
                Me("vr_1200") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property enable_fog() As Boolean
            Get
                Return CType(Me("enable_fog"),Boolean)
            End Get
            Set
                Me("enable_fog") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property load_extra() As Boolean
            Get
                Return CType(Me("load_extra"),Boolean)
            End Get
            Set
                Me("load_extra") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property txt_256() As Boolean
            Get
                Return CType(Me("txt_256"),Boolean)
            End Get
            Set
                Me("txt_256") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("192.168.24.100")>  _
        Public Property my_wan_ip() As String
            Get
                Return CType(Me("my_wan_ip"),String)
            End Get
            Set
                Me("my_wan_ip") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1953")>  _
        Public Property dispatch_port() As String
            Get
                Return CType(Me("dispatch_port"),String)
            End Get
            Set
                Me("dispatch_port") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property save_pw() As Boolean
            Get
                Return CType(Me("save_pw"),Boolean)
            End Get
            Set
                Me("save_pw") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property password() As String
            Get
                Return CType(Me("password"),String)
            End Get
            Set
                Me("password") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Terry Bosio")>  _
        Public Property username() As String
            Get
                Return CType(Me("username"),String)
            End Get
            Set
                Me("username") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1956")>  _
        Public Property game_port() As String
            Get
                Return CType(Me("game_port"),String)
            End Get
            Set
                Me("game_port") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property lod0() As Boolean
            Get
                Return CType(Me("lod0"),Boolean)
            End Get
            Set
                Me("lod0") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property chat_local() As Global.System.Drawing.Point
            Get
                Return CType(Me("chat_local"),Global.System.Drawing.Point)
            End Get
            Set
                Me("chat_local") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("60")>  _
        Public Property ambient_level() As Integer
            Get
                Return CType(Me("ambient_level"),Integer)
            End Get
            Set
                Me("ambient_level") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("60")>  _
        Public Property model_level() As Integer
            Get
                Return CType(Me("model_level"),Integer)
            End Get
            Set
                Me("model_level") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("60")>  _
        Public Property tree_level() As Integer
            Get
                Return CType(Me("tree_level"),Integer)
            End Get
            Set
                Me("tree_level") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("300")>  _
        Public Property minimap_size() As Single
            Get
                Return CType(Me("minimap_size"),Single)
            End Get
            Set
                Me("minimap_size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property icon_scale() As Single
            Get
                Return CType(Me("icon_scale"),Single)
            End Get
            Set
                Me("icon_scale") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Unchecked")>  _
        Public Property low_q_trees() As Global.System.Windows.Forms.CheckState
            Get
                Return CType(Me("low_q_trees"),Global.System.Windows.Forms.CheckState)
            End Get
            Set
                Me("low_q_trees") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("50")>  _
        Public Property s_terrian_texture_level() As Integer
            Get
                Return CType(Me("s_terrian_texture_level"),Integer)
            End Get
            Set
                Me("s_terrian_texture_level") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("50")>  _
        Public Property s_terrain_ambient_level() As Integer
            Get
                Return CType(Me("s_terrain_ambient_level"),Integer)
            End Get
            Set
                Me("s_terrain_ambient_level") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("15")>  _
        Public Property s_fog_level() As Integer
            Get
                Return CType(Me("s_fog_level"),Integer)
            End Get
            Set
                Me("s_fog_level") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property s_model_level() As Integer
            Get
                Return CType(Me("s_model_level"),Integer)
            End Get
            Set
                Me("s_model_level") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("dec7th_1941")>  _
        Public Property lidgren_pw() As String
            Get
                Return CType(Me("lidgren_pw"),String)
            End Get
            Set
                Me("lidgren_pw") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\games\World_of_Tanks\")>  _
        Public Property game_path() As String
            Get
                Return CType(Me("game_path"),String)
            End Get
            Set
                Me("game_path") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Checked")>  _
        Public Property m_show_tank_names() As Global.System.Windows.Forms.CheckState
            Get
                Return CType(Me("m_show_tank_names"),Global.System.Windows.Forms.CheckState)
            End Get
            Set
                Me("m_show_tank_names") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Checked")>  _
        Public Property m_show_tank_comments() As Global.System.Windows.Forms.CheckState
            Get
                Return CType(Me("m_show_tank_comments"),Global.System.Windows.Forms.CheckState)
            End Get
            Set
                Me("m_show_tank_comments") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property hi_rez_terra() As Boolean
            Get
                Return CType(Me("hi_rez_terra"),Boolean)
            End Get
            Set
                Me("hi_rez_terra") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property m_bumpMap() As Boolean
            Get
                Return CType(Me("m_bumpMap"),Boolean)
            End Get
            Set
                Me("m_bumpMap") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property m_bump_map_models() As Boolean
            Get
                Return CType(Me("m_bump_map_models"),Boolean)
            End Get
            Set
                Me("m_bump_map_models") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("50")>  _
        Public Property s_gamma() As Integer
            Get
                Return CType(Me("s_gamma"),Integer)
            End Get
            Set
                Me("s_gamma") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property m_show_uv2() As Boolean
            Get
                Return CType(Me("m_show_uv2"),Boolean)
            End Get
            Set
                Me("m_show_uv2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property s_gray_level() As Integer
            Get
                Return CType(Me("s_gray_level"),Integer)
            End Get
            Set
                Me("s_gray_level") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property m_show_decals() As Boolean
            Get
                Return CType(Me("m_show_decals"),Boolean)
            End Get
            Set
                Me("m_show_decals") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property m_load_terrain() As Boolean
            Get
                Return CType(Me("m_load_terrain"),Boolean)
            End Get
            Set
                Me("m_load_terrain") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property m_load_trees() As Boolean
            Get
                Return CType(Me("m_load_trees"),Boolean)
            End Get
            Set
                Me("m_load_trees") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property m_load_models() As Boolean
            Get
                Return CType(Me("m_load_models"),Boolean)
            End Get
            Set
                Me("m_load_models") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property m_load_decals() As Boolean
            Get
                Return CType(Me("m_load_decals"),Boolean)
            End Get
            Set
                Me("m_load_decals") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property m_bases() As Boolean
            Get
                Return CType(Me("m_bases"),Boolean)
            End Get
            Set
                Me("m_bases") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property m_water() As Boolean
            Get
                Return CType(Me("m_water"),Boolean)
            End Get
            Set
                Me("m_water") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property m_sky() As Boolean
            Get
                Return CType(Me("m_sky"),Boolean)
            End Get
            Set
                Me("m_sky") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property m_small_lights() As Boolean
            Get
                Return CType(Me("m_small_lights"),Boolean)
            End Get
            Set
                Me("m_small_lights") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property m_FXAA() As Boolean
            Get
                Return CType(Me("m_FXAA"),Boolean)
            End Get
            Set
                Me("m_FXAA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SSAO() As Boolean
            Get
                Return CType(Me("SSAO"),Boolean)
            End Get
            Set
                Me("SSAO") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property m_constant_updates() As Boolean
            Get
                Return CType(Me("m_constant_updates"),Boolean)
            End Get
            Set
                Me("m_constant_updates") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Terra.My.MySettings
            Get
                Return Global.Terra.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
